"""add chunk chapter and parent_heading columns

Revision ID: 3579bf44957f
Revises: 030e1a4b14fa
Create Date: 2026-03-08 17:40:06.771073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3579bf44957f'
down_revision: Union[str, None] = '030e1a4b14fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('textbook_chunks', sa.Column('chapter', sa.String(length=500), nullable=True))
    op.add_column('textbook_chunks', sa.Column('parent_heading', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('textbook_chunks', 'parent_heading')
    op.drop_column('textbook_chunks', 'chapter')
    # ### end Alembic commands ###
