"""Add role to User and edit_history_json to Exam

Revision ID: fe39fdc8172a
Revises: a1b2c3d4e5f6
Create Date: 2026-03-17 09:57:34.251162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe39fdc8172a'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('edit_history_json', sa.JSON(), nullable=True))
    op.add_column(
        'users',
        sa.Column(
            'role',
            sa.String(length=50),
            nullable=False,
            server_default='lecturer',
        ),
    )
    op.execute("UPDATE users SET role = 'lecturer' WHERE role IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('exams', 'edit_history_json')
    # ### end Alembic commands ###
