"""add course_id to documents

Revision ID: bd3064db5e63
Revises: 001
Create Date: 2026-04-03 15:50:22.962503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bd3064db5e63'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('course_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_documents_course_id'), 'documents', ['course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_course_id'), table_name='documents')
    op.drop_column('documents', 'course_id')
    # ### end Alembic commands ###
